### ISSUE TITLE
Add option to not delete source/build directories

### ISSUE THREAD

**Issue by sdobbs** [JeffersonLab/hdpm#3]
It would be helpful to add an option to not delete the build directories for those packages that are currently handled like this (e.g. root/geant4), in order to help with diagnosing build problems

**Comment by sparksn** [comment]
This option has already landed in the development version.
The command that deletes the build directory was moved into the package settings file.
You can fetch the development version by running:
`hdpm fetch hdpm@dev`

I am planning on releasing `hdpm 0.4.0` soon.

**Comment by sdobbs** [comment]
Okay, glad to hear it!  I'll look forward to the new version.
