### ISSUE TITLE
Use relative symlinks in pkgs/

### ISSUE THREAD

**Issue by sdobbs** [JeffersonLab/hdpm#4]
When symlinking directories to pkgs/PACKAGE/VERSION from pkgs/.dist/PACKAGE/VERSION, it would be useful to symlink relative paths instead of absolute paths.  This would help when moving hdpm directories around, or dealing with odd NFS problems.

**Comment by sparksn** [comment]
I agree that using relative paths in the symlinks would be better.
I have applied this change in my development version, and I am testing it now.

**Comment by sparksn** [comment]
Resolved by commit https://github.com/JeffersonLab/hdpm/commit/52031e1c3acf93463ed9bbd583de05174b144634.
